name: "go-run-schedule"

on:
  schedule:
    - cron: "0 */8 * * *"

jobs:
  go-run-schedule:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Setup Git Project"
        uses: "actions/checkout@v4"

      - name: "Setup Go Env"
        uses: "actions/setup-go@v4"
        with:
          cache: true
          go-version: "1.20.1"

      - name: "Update Historical Prices"
        env:
          AWS_ACCESS_KEY: "${{ secrets.AWS_ACCESS_KEY }}"
          AWS_SECRET_KEY: "${{ secrets.AWS_SECRET_KEY }}"
          AWS_REGION: "eu-central-1"
        run: |
          go run main.go upl
